# Generated by Django 3.1.7 on 2022-01-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallmanager',
            name='phone_number',
            field=models.CharField(default='03214123882', max_length=14),
        ),
    ]
